version: '3.8'

services:
  potential-nav:
    image: potential-nav:0.0
    container_name: potential-nav
    network_mode: host
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./src:/root/ros_ws/src
    stdin_open: true